apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: zetterstrom-dev
build:
  artifacts:
    - image: viktorzetterstrom/index-zetterstrom-dev
      context: packages/index
      sync:
        infer:
          - '**/*.html'
          - '**/*.js'
          - '**/*.css'
      docker:
        dockerfile: Dockerfile.dev
    - image: viktorzetterstrom/movies-zetterstrom-dev
      context: .
      sync:
        manual:
          - src: packages/movies/**/*.ts
            dest: /workspace/packages/movies
          - src: packages/movies/**/*.css
            dest: /workspace/packages/movies
          - src: packages/movies/**/*.html
            dest: /workspace/packages/movies
      docker:
        dockerfile: packages/movies/Dockerfile.dev
    - image: viktorzetterstrom/recipes-zetterstrom-dev
      context: .
      sync:
        manual:
          - src: packages/recipes/src/**/*
            dest: /workspace/packages/recipes/src
          - src: packages/recipes/utils/**/*
            dest: /workspace/packages/recipes/utils
          - src: packages/recipes/recipes/**/*.yaml
            dest: /workspace/packages/recipes/recipes
          - src: packages/recipes/recipes/**/*.yml
            dest: /workspace/packages/recipes/recipes
          - src: packages/recipes/public/**/*
            dest: /workspace/packages/recipes/public
      docker:
        dockerfile: packages/recipes/Dockerfile.dev
  local:
    push: false
manifests:
  rawYaml:
    - k8s/namespace.yaml
    - k8s/local-tls-secret.yaml
    - k8s/ingress-srv.yaml
    - k8s/index-depl.yaml
    - k8s/movies-depl.yaml
    - k8s/recipes-depl.yaml
deploy:
  kubectl: {}
  kubeContext: docker-desktop
portForward:
  - resourceType: service
    resourceName: index-srv
    namespace: z-dev
    port: 80
    localPort: 3000
  - resourceType: service
    resourceName: recipes-srv
    namespace: z-dev
    port: 80
    localPort: 3001
  - resourceType: service
    resourceName: movies-srv
    namespace: z-dev
    port: 80
    localPort: 3002
