apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: zetterstrom-dev
build:
  local:
    push: false
  artifacts:
    - image: viktorzetterstrom/index-zetterstrom-dev
      context: index
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.html"
          - "**/*.js"
          - "**/*.css"
    - image: viktorzetterstrom/movies-zetterstrom-dev
      context: movies
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.ts"
          - "**/*.css"
          - "**/*.html"
    - image: viktorzetterstrom/recipes-zetterstrom-dev
      context: recipes
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
          - "**/*.ts"
          - "**/*.tsx"
          - "**/*.css"
deploy:
  kubeContext: docker-desktop
  kubectl:
    manifests:
      - k8s/namespace.yaml
      - k8s/index-depl.yaml
      - k8s/movies-depl.yaml
      - k8s/recipes-depl.yaml
portForward:
  - resourceType: service
    resourceName: index-srv
    namespace: z-dev
    port: 80
    localPort: 3000
  - resourceType: service
    resourceName: recipes-srv
    namespace: z-dev
    port: 80
    localPort: 3001
  - resourceType: service
    resourceName: movies-srv
    namespace: z-dev
    port: 80
    localPort: 3002
