module.exports = {
  FHC: 'Frölunda',
  DIF: 'Djurgården',
  BIF: 'Brynäs',
  FBK: 'Färjestad',
  HV71: 'HV71',
  LHC: 'Linköping',
  LHF: 'Luleå',
  MIF: 'Malmö',
  OHK: 'Örebro',
  RBK: 'Rögle',
  SAIK: 'Skellefteå',
  VLH: 'Växjö',
  LIF: 'Leksand',
  IKO: 'Oskarshamn',
};
