apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address for ACME registration
    email: viktorzetterstrom@gmail.com
    # Secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # HTTP01 challenge for domain validation
    solvers:
      - http01:
          ingress:
            class: nginx
